server
{
  listen 3333;
  root /usr/share/nginx/html;

  location /api {
    proxy_pass http://carrier-rest-service:8080;
  }

  location / {
     try_files $uri $uri/ /index.html;  # 將未匹配的請求重定向到 index.html
  }
}
