import ViewGroup from './view-group'
import DocsView from './docs-view'
import DocsUploadView from './docs-upload-view'
import ResponseObject from '../interfaces/response-object'
import { ViewId } from '../enums'
import Picker from './picker'

/**
 * {@link PickerBuilder} is used to create {@link Picker} objects. Except where noted otherwise, the return type of methods below is of type {@link PickerBuilder}, allowing you to chain one call after another.
 * @example
 * const picker = new google.pickerPickerBuilder()
 *  .setOAuthToken('TOKEN_FOR_USER')
 *  .setAppId('1234567890')  // Cloud Project number
 *  .addView(google.picker.ViewId.DOCS)
 *  .setCallback((data) => {
 *    console.log(data);
 *  })
  .build();
 *
 * @see https://developers.google.com/drive/picker/reference/picker.pickerbuilder.md
 */
export default class PickerBuilder {
  constructor()
  /**
   * Add a view to the navigation pane.
   */
  addView(viewOrViewId: DocsView | DocsUploadView | ViewId): PickerBuilder
  /**
   * Add a ViewGroup to the top-level navigation pane.
   */
  addViewGroup(viewGroup: ViewGroup): PickerBuilder
  /**
   * Construct the Picker object.
   */
  build(): Picker
  /**
   * Disable a picker feature.
   */
  disableFeature(feature: string): PickerBuilder
  /**
   * Enable a picker feature.
   */
  enableFeature(feature: string): PickerBuilder
  /**
   * Get the relay URL, used for gadgets.rpc.
   */
  getRelayUrl(): string
  /**
   * Get the dialog title.
   */
  getTitle(): string
  /**
   * Disable the title bar from being shown. To re-enable, call setTitle with a non-empty title or undefined.
   */
  hideTitleBar(): PickerBuilder
  /**
   * Check if a picker Feature is enabled.
   */
  isFeatureEnabled(feature: string): boolean
  /**
   * Sets the Id of the application needing to access the user's files via the Drive API.
   */
  setAppId(appId: string): PickerBuilder
  /**
   * Set the callback method. This method is called when the user selects items or cancels. The callback method receives a single callback object. The structure of the callback object is described in the [JSON Guide](./response-object.ts).
   */
  setCallback(method: (result: ResponseObject) => void): PickerBuilder
  /**
   * Sets the Browser API key obtained from Google Developers Console. See the Developer's Guide for details on how to obtain the Browser API key.
   */
  setDeveloperKey(key: string): PickerBuilder
  /**
   * Set the document.
   */
  setDocument(document: DocsView): PickerBuilder
  /**
   * Set the locale for the picker. The locale is an ISO 639 language code. If the language is not supported, en-US is used.
   */
  setLocale(locale: string): PickerBuilder
  /**
   * Sets the maximum number of items a user can pick.
   */
  setMaxItems(max: number): PickerBuilder
  /**
   * Sets an OAuth token to use for authenticating the current user.
   */
  setOAuthToken(token: string): PickerBuilder
  /**
   * Sets the origin of picker dialog. The origin should be set to the window.location.protocol + '//' + window.location.host of the top-most page, if your application is running in an iframe.
   */
  setOrigin(origin: string): PickerBuilder
  /**
   * Set the relay URL, used for gadgets.rpc.
   */
  setRelayUrl(url: string): PickerBuilder
  /**
   * Set the list of MIME types which will be selectable. Use commas to separate MIME types if more than one is required. If you don't set MIME types, files of all MIME types are displayed in the view.
   */
  setSelectableMimeTypes(type: string): PickerBuilder
  /**
   * Set the preferred dialog size. The dialog will be auto-centered. It has a minimum size of (566,350) and a maximum size of (1051,650).
   */
  setSize(width: number, height: number): PickerBuilder
  /**
   * Set the dialog title.
   */
  setTitle(title: string): PickerBuilder
  /**
   * Returns the URI generated by this builder.
   */
  toUri(): string
}
